services:
  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 8300:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src
        - path: ./package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173
 